// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		BasicCard: typeof import('./components/workbench/basicCard.vue')['default'];
		ChartCard: typeof import('./components/workbench/chartCard.vue')['default'];
		ElAside: typeof import('element-plus/es')['ElAside'];
		ElAvatar: typeof import('element-plus/es')['ElAvatar'];
		ElBadge: typeof import('element-plus/es')['ElBadge'];
		ElButton: typeof import('element-plus/es')['ElButton'];
		ElCard: typeof import('element-plus/es')['ElCard'];
		ElCol: typeof import('element-plus/es')['ElCol'];
		ElContainer: typeof import('element-plus/es')['ElContainer'];
		ElDivider: typeof import('element-plus/es')['ElDivider'];
		ElForm: typeof import('element-plus/es')['ElForm'];
		ElFormItem: typeof import('element-plus/es')['ElFormItem'];
		ElHeader: typeof import('element-plus/es')['ElHeader'];
		ElIcon: typeof import('element-plus/es')['ElIcon'];
		ElImage: typeof import('element-plus/es')['ElImage'];
		ElInput: typeof import('element-plus/es')['ElInput'];
		ElMain: typeof import('element-plus/es')['ElMain'];
		ElMenu: typeof import('element-plus/es')['ElMenu'];
		ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
		ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup'];
		ElPopover: typeof import('element-plus/es')['ElPopover'];
		ElRow: typeof import('element-plus/es')['ElRow'];
		ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
		ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
		ElTooltip: typeof import('element-plus/es')['ElTooltip'];
		IEpSearch: typeof import('~icons/ep/search')['default'];
		IEpUser: typeof import('~icons/ep/user')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
	}
}
